services:
  db:
    image: postgres:16-alpine
    container_name: offlinedocs_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-offline_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-securepath}
      POSTGRES_DB: ${DB_NAME:-offlinedocs}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # We will add Redis later in Phase 2

volumes:
  postgres_data: